[URL]
Protocol=unreal
ProtocolDescription=Unreal Protocol
Name=Player
Map=Index.unr
LocalMap=CityIntro.unr
Host=
Portal=
MapExt=unr
SaveExt=usa
Port=7777
Class=Botpack.TMale1

[FirstRun]
FirstRun=0

[PackageRemap]
UnrealShare=UnrealI

[Engine.Engine]
GameRenderDevice=OpenGLDrv.OpenGLRenderDevice
AudioDevice=ALAudio.ALAudioSubsystem
NetworkDevice=IpDrv.TcpNetDriver
DemoRecordingDevice=udemo.udemodriver
Console=UTMenu.UTConsole
Language=int
GameEngine=Engine.GameEngine
EditorEngine=Editor.EditorEngine
WindowedRenderDevice=OpenGLDrv.OpenGLRenderDevice
RenderDevice=OpenGLDrv.OpenGLRenderDevice
DefaultGame=Botpack.DeathMatchPlus
DefaultServerGame=Botpack.DeathMatchPlus
ViewportManager=WinDrv.WindowsClient
Render=Render.Render
Input=Engine.Input
Canvas=Engine.Canvas
CdPath=G:

[Core.System]
PurgeCacheDays=30
SavePath=../Save
CachePath=../Cache
CacheExt=.uxx
Paths=../System/*.u
Paths=../Maps/*.unr
Paths=../Textures/*.utx
Paths=../Sounds/*.uax
Paths=../Music/*.umx
Suppress=DevLoad
Suppress=DevSave
Suppress=DevNetTraffic
Suppress=DevGarbage
Suppress=DevKill
Suppress=DevReplace
Suppress=DevSound
Suppress=DevCompile
Suppress=DevBind
Suppress=DevBsp
Suppress=DevMD5
Suppress=DevAudio
Suppress=DevMusic

[Editor.EditorEngine]
EditPackages=Core
EditPackages=Engine
; EditPackages=Editor
; EditPackages=UWindow
; EditPackages=Fire
; EditPackages=IpDrv
; EditPackages=UWeb
; EditPackages=UBrowser
; EditPackages=UnrealShare
EditPackages=UnrealI
; EditPackages=UMenu
EditPackages=Botpack
; EditPackages=IpServer
; EditPackages=UTServerAdmin
; EditPackages=UTMenu
; EditPackages=UTBrowser
EditPackages=FFNArena
EditPackages=TestFFNArena
